os: linux
dist: xenial
sudo: required
git:
  depth: 3
addons:
  apt:
    update:
    - true
services:
  - docker
before_install:
  - docker pull yshalsager/cyanogenmod:latest
before_script:
  - cd $HOME && mkdir twrp
  - wget -q https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.2.3-20180830/MinimalOmniRecovery-twrp-6.0-norepo-20180830.tar.xz
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:  
  - cd $HOME/twrp/ && git clone https://github.com/izackon/android_device_LANIX_Ilium_M1.git device/LANIX/Ilium_M1
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
   - git clone https://github.com/ZeoRexDevs/device_generic_mtk_twrpbuilder device/generic/twrpbuilder
- |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/cmbuild/twrp/:rw,z" yshalsager/cyanogenmod bash << EOF
    cd /home/cmbuild/twrp/
    source build/envsetup.sh && lunch omni_Ilium_M1-eng && mka recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/Ilium_M1/recovery.img $HOME/twrp/TWRP-$version-Ilium_M1-$(date +"%Y%m%d")-Unofficial.img
  - cd $HOME/twrp/
  - curl -s --upload-file TWRP-$version-Ilium_M1-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GitOAUTHToken
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: izackon/android_device_LANIX_Ilium_M1
    branch: master
branches:
  only:
  - master
  except:
  - /^(?i:untagged)-.*$/
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
